# Generated by Django 4.2.1 on 2023-05-19 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_of_event', models.ImageField(upload_to='event-image')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('name_of_pharmacy', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pharmacy_email', models.CharField(max_length=100)),
                ('pharmacy_phone_number', models.CharField(max_length=100)),
                ('description_about_location', models.TextField()),
                ('address_or_location', models.CharField(max_length=255)),
                ('image_of_pharmacy', models.ImageField(upload_to='pharmacy-image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stamped_application', models.ImageField(upload_to='pharm')),
                ('certificate_of_nationality_not_less_than_3_months', models.ImageField(upload_to='pharm')),
                ('certified_birth_certificate_not_less_than_3_months', models.ImageField(upload_to='pharm')),
                ('certified_copy_of_decorate_degree_in_pharmacy', models.ImageField(upload_to='pharm')),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.pharmacy')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('name_of_drug', models.CharField(max_length=255)),
                ('description_of_drug', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image_of_drug', models.ImageField(upload_to='drug-image')),
                ('is_available', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pharmacy', models.ManyToManyField(to='base.pharmacy')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
            },
        ),
    ]
